name = "hexo-sharp"
main = "dist/worker.js"
compatibility_date = "2023-05-18"
workers_dev = true

# KV 命名空间绑定
[[kv_namespaces]]
binding = "HSPKV"
id = "PRESERVED_FOR_ACTIONS"

# 静态资源（前端构建产物）
[assets]
directory = "./dist"
